title: David G. Kamper
logo: /assets/img/Michiganheadshot.jpeg
description: Law, Cognition, Computation, Creativity, Aesthetics, Morality, Experimental Jurisprudence, Intellectual Property, Tort
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
