title: David G. Kamper
logo: /assets/img/6ECC849C-EABB-4534-BA61-6C471A6BED6F_1_105_c.jpeg
description: PhD Student in Cognitive Neuroscience and Computational Cognitive Science.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
