title: David G. Kamper
logo: /assets/img/logo.png
description: PhD Student in Cognitive Neuroscience and Computational Cognitive Science.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
