title: David G. Kamper
logo: /assets/img/6ECC849C-EABB-4534-BA61-6C471A6BED6F_1_105_c.png
description: Law, Cognition, Computation, Creativity, Aesthetics, Experimental Jurisprudence, Intellectual Property, Tort
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
